/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthenticatedServiceClaimIndexRouteImport } from './routes/_authenticated/service-claim/index'
import { Route as AuthenticatedSectorManagementIndexRouteImport } from './routes/_authenticated/sector-management/index'
import { Route as AuthenticatedIdManagementIndexRouteImport } from './routes/_authenticated/id-management/index'
import { Route as AuthenticatedServiceClaimServiceIDRouteImport } from './routes/_authenticated/service-claim/$serviceID'
import { Route as AuthenticatedSectorManagementSectorIDRouteImport } from './routes/_authenticated/sector-management/$sectorID'
import { Route as AuthenticatedIdManagementIssuanceRouteImport } from './routes/_authenticated/id-management/issuance'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/_public/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedServiceClaimIndexRoute =
  AuthenticatedServiceClaimIndexRouteImport.update({
    id: '/service-claim/',
    path: '/service-claim/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSectorManagementIndexRoute =
  AuthenticatedSectorManagementIndexRouteImport.update({
    id: '/sector-management/',
    path: '/sector-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIdManagementIndexRoute =
  AuthenticatedIdManagementIndexRouteImport.update({
    id: '/id-management/',
    path: '/id-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServiceClaimServiceIDRoute =
  AuthenticatedServiceClaimServiceIDRouteImport.update({
    id: '/service-claim/$serviceID',
    path: '/service-claim/$serviceID',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSectorManagementSectorIDRoute =
  AuthenticatedSectorManagementSectorIDRouteImport.update({
    id: '/sector-management/$sectorID',
    path: '/sector-management/$sectorID',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIdManagementIssuanceRoute =
  AuthenticatedIdManagementIssuanceRouteImport.update({
    id: '/id-management/issuance',
    path: '/id-management/issuance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof PublicLoginRoute
  '/id-management/issuance': typeof AuthenticatedIdManagementIssuanceRoute
  '/sector-management/$sectorID': typeof AuthenticatedSectorManagementSectorIDRoute
  '/service-claim/$serviceID': typeof AuthenticatedServiceClaimServiceIDRoute
  '/id-management/': typeof AuthenticatedIdManagementIndexRoute
  '/sector-management/': typeof AuthenticatedSectorManagementIndexRoute
  '/service-claim/': typeof AuthenticatedServiceClaimIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof PublicLoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/id-management/issuance': typeof AuthenticatedIdManagementIssuanceRoute
  '/sector-management/$sectorID': typeof AuthenticatedSectorManagementSectorIDRoute
  '/service-claim/$serviceID': typeof AuthenticatedServiceClaimServiceIDRoute
  '/id-management': typeof AuthenticatedIdManagementIndexRoute
  '/sector-management': typeof AuthenticatedSectorManagementIndexRoute
  '/service-claim': typeof AuthenticatedServiceClaimIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/id-management/issuance': typeof AuthenticatedIdManagementIssuanceRoute
  '/_authenticated/sector-management/$sectorID': typeof AuthenticatedSectorManagementSectorIDRoute
  '/_authenticated/service-claim/$serviceID': typeof AuthenticatedServiceClaimServiceIDRoute
  '/_authenticated/id-management/': typeof AuthenticatedIdManagementIndexRoute
  '/_authenticated/sector-management/': typeof AuthenticatedSectorManagementIndexRoute
  '/_authenticated/service-claim/': typeof AuthenticatedServiceClaimIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/id-management/issuance'
    | '/sector-management/$sectorID'
    | '/service-claim/$serviceID'
    | '/id-management/'
    | '/sector-management/'
    | '/service-claim/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/id-management/issuance'
    | '/sector-management/$sectorID'
    | '/service-claim/$serviceID'
    | '/id-management'
    | '/sector-management'
    | '/service-claim'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public/login'
    | '/_authenticated/'
    | '/_authenticated/id-management/issuance'
    | '/_authenticated/sector-management/$sectorID'
    | '/_authenticated/service-claim/$serviceID'
    | '/_authenticated/id-management/'
    | '/_authenticated/sector-management/'
    | '/_authenticated/service-claim/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicLoginRoute: typeof PublicLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/service-claim/': {
      id: '/_authenticated/service-claim/'
      path: '/service-claim'
      fullPath: '/service-claim/'
      preLoaderRoute: typeof AuthenticatedServiceClaimIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sector-management/': {
      id: '/_authenticated/sector-management/'
      path: '/sector-management'
      fullPath: '/sector-management/'
      preLoaderRoute: typeof AuthenticatedSectorManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/id-management/': {
      id: '/_authenticated/id-management/'
      path: '/id-management'
      fullPath: '/id-management/'
      preLoaderRoute: typeof AuthenticatedIdManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service-claim/$serviceID': {
      id: '/_authenticated/service-claim/$serviceID'
      path: '/service-claim/$serviceID'
      fullPath: '/service-claim/$serviceID'
      preLoaderRoute: typeof AuthenticatedServiceClaimServiceIDRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sector-management/$sectorID': {
      id: '/_authenticated/sector-management/$sectorID'
      path: '/sector-management/$sectorID'
      fullPath: '/sector-management/$sectorID'
      preLoaderRoute: typeof AuthenticatedSectorManagementSectorIDRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/id-management/issuance': {
      id: '/_authenticated/id-management/issuance'
      path: '/id-management/issuance'
      fullPath: '/id-management/issuance'
      preLoaderRoute: typeof AuthenticatedIdManagementIssuanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedIdManagementIssuanceRoute: typeof AuthenticatedIdManagementIssuanceRoute
  AuthenticatedSectorManagementSectorIDRoute: typeof AuthenticatedSectorManagementSectorIDRoute
  AuthenticatedServiceClaimServiceIDRoute: typeof AuthenticatedServiceClaimServiceIDRoute
  AuthenticatedIdManagementIndexRoute: typeof AuthenticatedIdManagementIndexRoute
  AuthenticatedSectorManagementIndexRoute: typeof AuthenticatedSectorManagementIndexRoute
  AuthenticatedServiceClaimIndexRoute: typeof AuthenticatedServiceClaimIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedIdManagementIssuanceRoute:
    AuthenticatedIdManagementIssuanceRoute,
  AuthenticatedSectorManagementSectorIDRoute:
    AuthenticatedSectorManagementSectorIDRoute,
  AuthenticatedServiceClaimServiceIDRoute:
    AuthenticatedServiceClaimServiceIDRoute,
  AuthenticatedIdManagementIndexRoute: AuthenticatedIdManagementIndexRoute,
  AuthenticatedSectorManagementIndexRoute:
    AuthenticatedSectorManagementIndexRoute,
  AuthenticatedServiceClaimIndexRoute: AuthenticatedServiceClaimIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicLoginRoute: PublicLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
