/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiceClaimRouteImport } from './routes/service-claim'
import { Route as IdRegistrationRouteImport } from './routes/id-registration'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const ServiceClaimRoute = ServiceClaimRouteImport.update({
  id: '/service-claim',
  path: '/service-claim',
  getParentRoute: () => rootRouteImport,
} as any)
const IdRegistrationRoute = IdRegistrationRouteImport.update({
  id: '/id-registration',
  path: '/id-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/id-registration': typeof IdRegistrationRoute
  '/service-claim': typeof ServiceClaimRoute
  '/login': typeof authLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/id-registration': typeof IdRegistrationRoute
  '/service-claim': typeof ServiceClaimRoute
  '/login': typeof authLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/id-registration': typeof IdRegistrationRoute
  '/service-claim': typeof ServiceClaimRoute
  '/(auth)/login': typeof authLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/id-registration' | '/service-claim' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/id-registration' | '/service-claim' | '/login'
  id: '__root__' | '/' | '/id-registration' | '/service-claim' | '/(auth)/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdRegistrationRoute: typeof IdRegistrationRoute
  ServiceClaimRoute: typeof ServiceClaimRoute
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/service-claim': {
      id: '/service-claim'
      path: '/service-claim'
      fullPath: '/service-claim'
      preLoaderRoute: typeof ServiceClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/id-registration': {
      id: '/id-registration'
      path: '/id-registration'
      fullPath: '/id-registration'
      preLoaderRoute: typeof IdRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdRegistrationRoute: IdRegistrationRoute,
  ServiceClaimRoute: ServiceClaimRoute,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
